# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_announcement_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='upper_node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.Place'),
        ),
    ]
