# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_auto_20171209_1722'),
        ('admin_dashboard', '0009_auto_20171209_1736'),
    ]

    operations = [
    ]
