# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_auto_20171209_2054'),
        ('admin_dashboard', '0010_merge_20171209_1805'),
    ]

    operations = [
    ]
