# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20171210_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
